### PR TITLE
Add some Play 2.4-friendly overloads

### PR DESCRIPTION
**Pull request by cb372**
If you're using Play 2.4 with compile-time DI, it's a little tricky to use play-googleauth in its current state because it depends on extracting the WS client from the currently running app. This means:

* you need to import `Play.current`, which is frowned upon in Play 2.4
* you have to add the WS components to the application's injector

Added some overloads that allow you to pass a WS client (or rather a `WSAPI`, to be precise) explicitly, which avoids this mess.

Ideally `GoogleAuth` should be an injectable component, not an `object`, but I'm going with this easier fix for now.

### CODE REVIEW

**Comment by philwills** [comment]
Injectors make me sad.

**Comment by philwills** [comment]
This annoys me because there's no need for WS to be stateful at all, but I don't feel quite angry enough to say no to your perfectly reasonable implementation.

**Comment by rtyley** [comment]
I've been using http://square.github.io/okhttp/ as alternative Http client because

* It had support for SNI while other Java clients didn't, at least for a while
* It supports Etags & If-Modified-Since with a local disk cache (handy for calling the GitHub API and not burning API quota)
* It meant I didn't have to muck around with implicit Applications or injectors...

Your pull request looks fine to me tho'

**Comment by cb372** [comment]
By the way, here's a taste of the kind of fun you can expect using play-googleauth without this PR:

* [Add the WS stuff to your injector](https://github.com/guardian/content-api-dashboard/blob/master/app/AppComponents.scala#L38) if you want to avoid a NoSuchMethodError at runtime
* [Pass the application to controllers by-name](https://github.com/guardian/content-api-dashboard/blob/master/app/controllers/Auth.scala#L10) if you want to avoid a NullPointerException at runtime due to cyclic dependency madness

That's the great thing about Play's support for compile-time DI - it protects you from any surprises at ... erm ... oh.

@rtyley I agree about OkHttp. It's really nice.

Could somebody merge this please? I don't have permissions for some reason. Also a release would be nice, but no rush at all.

**Comment by philwills** [comment]
I've given you permission to merge if you want, but can do it and publish, if that would be simpler.

**Comment by cb372** [comment]
Thanks. Released v0.3.1

**Pull request merged**
